### ISSUE TITLE
一度ゲームオーバーになってから、ゲームをスタートすると、なにもしてないのにゲームオーバーになる

### ISSUE THREAD

**Issue by yokmama** [ryokno08/werewolfGame#12]
フラグなどがリセットされていないのでは？

**Comment by ZOIChannel** [comment]
```
[17:27:53 WARN]: [WerewolfGame] Task #16 for WerewolfGame v1.0-SNAPSHOT generated an exception
java.lang.IllegalStateException: Not scheduled yet
        at org.bukkit.scheduler.BukkitRunnable.checkScheduled(BukkitRunnable.java:149) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.scheduler.BukkitRunnable.getTaskId(BukkitRunnable.java:143) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.scheduler.BukkitRunnable.cancel(BukkitRunnable.java:29) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at jp.hack.minecraft.werewolfgame.Game.stop(Game.java:324) ~[?:?]
        at jp.hack.minecraft.werewolfgame.Game.playerDefeat(Game.java:312) ~[?:?]
        at jp.hack.minecraft.werewolfgame.Game.confirmGame(Game.java:286) ~[?:?]
        at jp.hack.minecraft.werewolfgame.core.state.PlayingState$1.run(PlayingState.java:60) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
```

**Comment by ZOIChannel** [comment]
```
[17:48:09 WARN]: [WerewolfGame] Task #16 for WerewolfGame v1.0-SNAPSHOT generated an exception
java.lang.IllegalStateException: Not scheduled yet
        at org.bukkit.scheduler.BukkitRunnable.checkScheduled(BukkitRunnable.java:149) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.scheduler.BukkitRunnable.getTaskId(BukkitRunnable.java:143) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.scheduler.BukkitRunnable.cancel(BukkitRunnable.java:29) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at jp.hack.minecraft.werewolfgame.Game.stop(Game.java:317) ~[?:?]
        at jp.hack.minecraft.werewolfgame.Game.playerVictory(Game.java:300) ~[?:?]
        at jp.hack.minecraft.werewolfgame.Game.confirmGame(Game.java:280) ~[?:?]
        at jp.hack.minecraft.werewolfgame.core.state.PlayingState$1.run(PlayingState.java:60) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
```
